# Makefile 
#

include ./user_build_config

all: user_build_config
	(cd build_upp;		make)
	(cd src;		make)
	(cd run;		make)

clean:
	(cd build_upp;		make clean)
	(cd src;		make clean)
	(cd run;		make clean)
